### ISSUE TITLE
Site

### ISSUE THREAD

**Issue by theo4850** [costasdroid/schoolMeteo#2]
Πριν από λίγο προσπάθησα να μπω στο site, αλλά δεν μπαίνει. Μήπως υπάρχει κάποιο θέμα με το site ή επειδή είχαμε κλείσει το raspberry;

**Comment by costasdroid** [comment]
Προσπαθώ να κάνω portforward στο 22 για ssh αλλά δεν τα καταφέρνω. Μέχρι στιγμής ο μόνος τρόπος για deploy είναι από ssh στο τοιπκό lan.
